#!/bin/bash

# Update before attempting install
sudo apt update

# Get wslpath
sudo apt install php
wget 'https://raw.githubusercontent.com/laurent22/wslpath/master/wslpath'
chmod 755 wslpath
sudo mv wslpath /usr/bin

# Get fish
sudo apt-add-repository ppa:fish-shell/release-2
sudo apt update
sudo apt install fish

# Get oh-my-fish
curl -L http://get.oh-my.fish | fish
