#!/bin/bash
#a###########################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles/                    # dotfiles directory
old_dir=~/dotfiles/old/            # old dotfiles backup directory

bashrc=.bashrc                     # file/target pairs for dotfiles
bashrc_t=~/

vimrc=.vimrc
vimrc_t=~/

rcconf=rc.conf
rcconf_t=~/.config/ranger/

rifleconf=rifle.conf
rifleconf_t=~/.config/ranger/

initfish=init.fish
initfish_t=~/.config/omf/

declare -a files=($bashrc $vimrc $rcconf $rifleconf $initfish)
declare -a targets=($bashrc_t $vimrc_t $rcconf_t $rifleconf_t $initfish_t)

##########

# create backup dotfiles directory
echo -n "Creating $old_dir for backup of any existing dotfiles ..."
mkdir -p $old_dir
echo "done"

# change to the dotfiles directory if not already there
echo -n "Changing to the $dir directory ..."
cd $dir
echo "done"

# backup existing dotfiles and symlink
for (( i=0; i<${#files[@]}; i++ ));
do
    echo "Moving any existing dotfiles to $old_dir"
    mv ${targets[$i]}${files[$i]} $old_dir
    echo "Creating symlink to ${targets[$i]}${files[$i]}"
    mkdir -p ${targets[$i]} && ln -s $dir${files[$i]} ${targets[$i]}${files[$i]}
done



