# atd
# Autogenerated from man page /usr/share/man/man8/atd.8.gz
complete -c atd -s l --description 'Specifies a limiting load factor, over which batch jobs should not be run, in…'
complete -c atd -s b --description 'Specify the minimum interval in seconds between the start of two batch jobs (…'
complete -c atd -s d --description 'Debug; print error messages to standard error instead of using  syslog(3) .'
complete -c atd -s f --description 'Run  atd in the foreground.'
complete -c atd -s s --description 'Process the at/batch queue only once.'

