# growpart
# Autogenerated from man page /usr/share/man/man1/growpart.1.gz
complete -c growpart -s h -l help --description 'Show usage and exit.'
complete -c growpart -s N -l dry-run --description 'Only report what would be done.'
complete -c growpart -l fudge --description 'Only modify partition table if the given partition would grow more than COUNT…'
complete -c growpart -s v -l verbose --description 'Give more information to stderr.'

