# ifenslave
# Autogenerated from man page /usr/share/man/man8/ifenslave.8.gz
complete -c ifenslave -s a --description 'Show information about all interfaces.'
complete -c ifenslave -s c --description 'Change active slave.'
complete -c ifenslave -s d --description 'Removes slave interfaces from the bonding device.'
complete -c ifenslave -s f --description 'Force actions to be taken if one of the specified interfaces appears not to b…'
complete -c ifenslave -s h --description 'Display a help message and exit.'
complete -c ifenslave -s u --description 'Show usage information and exit.'
complete -c ifenslave -s v --description 'Print warning and debug messages.'
complete -c ifenslave -s V --description 'Show version information and exit.'

