# ifenslave-2
# Autogenerated from man page /usr/share/man/man8/ifenslave-2.6.8.gz
complete -c ifenslave-2 -s a --description 'Show information about all interfaces.'
complete -c ifenslave-2 -s c --description 'Change active slave.'
complete -c ifenslave-2 -s d --description 'Removes slave interfaces from the bonding device.'
complete -c ifenslave-2 -s f --description 'Force actions to be taken if one of the specified interfaces appears not to b…'
complete -c ifenslave-2 -s h --description 'Display a help message and exit.'
complete -c ifenslave-2 -s u --description 'Show usage information and exit.'
complete -c ifenslave-2 -s v --description 'Print warning and debug messages.'
complete -c ifenslave-2 -s V --description 'Show version information and exit.'

