# lxc
# Autogenerated from man page /usr/share/man/man1/lxc.1.gz
complete -c lxc -l all --description 'Print less common commands.'
complete -c lxc -l debug --description 'Print debug information.'
complete -c lxc -l verbose --description 'Print verbose information.'
complete -c lxc -l version --description 'Show client version ENVIRONMENT.'

