# make-bcache
# Autogenerated from man page /usr/share/man/man8/make-bcache.8.gz
complete -c make-bcache -s C --description 'Create a cache.'
complete -c make-bcache -s B --description 'Create a backing device (kernel functionality not yet implemented).'
complete -c make-bcache -o UUUID --description 'Create a cache device with the specified UUID.'
complete -c make-bcache -s U --description 'Create a cache device with the specified UUID.'
complete -c make-bcache -s b --description 'Specifies the bucket size.'

