# probe-bcache
# Autogenerated from man page /usr/share/man/man8/probe-bcache.8.gz
complete -c probe-bcache -s o --description 'return UUID in udev style for invocation by udev rule as IMPORT{program} USAG…'

