# snap-confine
# Autogenerated from man page /usr/share/man/man1/snap-confine.1.gz
complete -c snap-confine -l classic --description 'applications are not confined at all (like in classic systems, hence the name…'
complete -c snap-confine -l base --description 'filesystem.  If omitted it defaults to the core snap.'

