# zerofree
# Autogenerated from man page /usr/share/man/man8/zerofree.8.gz
complete -c zerofree -s n --description 'Perform a dry run  (do not modify the file-system);.'
complete -c zerofree -s v --description 'Be verbose;.'

